apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: nexus-system
spec:
  template:
    spec:
      containers:
      - name: locust
        command:
        - locust
        - -f
        - /mnt/locust/locustfile.py
        - --headless
        - -u
        - "500"
        - -r
        - "50"
        - --run-time
        - 5m
        - --host
        - http://frontend.default.svc.cluster.local
